name: Build, Lint, Test and Scan

on:
  workflow_call:
    secrets:
      SONAR_TOKEN_WALLET_UI:
        required: true
      SONAR_TOKEN_STARKNET_SNAP:
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn --no-immutable

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Cache NPM tarballs
        id: cache-npm-tarballs
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.cache/npm
          key: npm-tarballs-${{ github.run_id }}
          restore-keys: |
            npm-tarballs
      - run: yarn --no-immutable
      - run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --no-immutable
      - run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --no-immutable
      - run: yarn build
      - run: yarn test
      - name: Cache Coverage Report
        uses: actions/cache@v3
        id: cache-coverage-report
        with:
          path: |
            ./packages/**/coverage
          key: ${{ github.sha }}-${{ matrix.node-version }}-coverage-report
  
  code-scan-snap:
    name: Scan Starknet Snap
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Restore Coverage Report
        uses: actions/cache@v3
        id: restore-coverage-report
        with:
          path: |
            ./packages/**/coverage
          key: ${{ github.sha }}-20.x-coverage-report

      - name: Download SonarScanner CLI
        run: |
          SC_VERSION=5.0.1.3006
          curl -sSLo /tmp/sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SC_VERSION}-linux.zip"
          unzip -q /tmp/sonar-scanner.zip -d /tmp
          echo "SONAR_SCANNER_BIN=/tmp/sonar-scanner-${SC_VERSION}-linux/bin/sonar-scanner" >> "$GITHUB_ENV"

      - name: SonarCloud Scan Starknet-Snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_STARKNET_SNAP }}
        run: |
          cd packages/starknet-snap
          NODE_PATH="$(which node)"
          echo "Using node: $NODE_PATH"
          "$SONAR_SCANNER_BIN" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.organization="consensys" \
            -Dsonar.projectKey="consensys_starknet-snap-starknet-snap" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.nodejs.executable="$NODE_PATH"
  
  code-scan-wallet-ui:
    name: Scan Wallet UI
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Restore Coverage Report
        uses: actions/cache@v3
        id: restore-coverage-report
        with:
          path: |
            ./packages/**/coverage
          key: ${{ github.sha }}-20.x-coverage-report

      - name: Download SonarScanner CLI
        run: |
          SC_VERSION=5.0.1.3006
          curl -sSLo /tmp/sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SC_VERSION}-linux.zip"
          unzip -q /tmp/sonar-scanner.zip -d /tmp
          echo "SONAR_SCANNER_BIN=/tmp/sonar-scanner-${SC_VERSION}-linux/bin/sonar-scanner" >> "$GITHUB_ENV"

      - name: SonarCloud Scan Wallet-UI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WALLET_UI }}
        run: |
          cd packages/wallet-ui
          NODE_PATH="$(which node)"
          echo "Using node: $NODE_PATH"
          "$SONAR_SCANNER_BIN" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.organization="consensys" \
            -Dsonar.projectKey="consensys_starknet-snap-wallet-ui" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.nodejs.executable="$NODE_PATH"
